from math import*
print('v1:')
v1=int(input())
print('v2:')
v2=int(input())
print('fora???:')
g=int(input())
t=g/(v2-v1)
hours=floor(t)
minutes=floor(t*60)
seconds=floor((t*60-minutes)*60)
time=[]
time.append(hours)
time.append(minutes)
time.append(seconds)
print(time)
